export const UPDATE_APP_STATE = "UPDATE_APP_STATE";

export const APP_STATE = {
  EDIT:"EDIT",
  VIEW:"VIEW",
  INDEX:"INDEX",
  PUBLIC:"PUBLIC",
  DASHBOARD:"DASHBOARD",
  INIT:"INIT"
}

export const PULL_PROFILE = "PULL_PROFILE";
export const EDIT_PROFILE = "EDIT_PROFILE";
export const SAVE_PROFILE = "SAVE_PROFILE";
export const CREATE_PROFILE = "CREATE_PROFILE";
export const PROFILE_PIC_UPLOAD = "PROFILE_PIC_UPLOAD";

export const NETWORK_STATUS = {
  SUCCESS:"SUCCESS",
  ERROR:"ERROR",
  LOADING:"LOADING",
  INIT:"INIT"
}

export const BLOCKS = {
  PROFILE:"PROFILE",
  QUOTE:"QUOTE",
  GALLERY:"GALLERY",
  DESCRIPTION:"DESCRIPTION",
  LINKS:"LINKS",
  ICONS:"ICONS",
  CTA:"CTA",
  LINE_BREAK:"LINE_BREAK",
  CHAT:"CHAT",
  ICON_ROW:"ICON_ROW",
  PROJECT:"PROJECT",
  HEADER:"HEADER",
  TABLE:"TABLE",
  INPUT:"INPUT",
  ADD:"ADD"
}

export const PULL_ARTICLES = "PULL_ARTICLES";

export const SET_CURRENT_ARTICLE = "SET_CURRENT_ARTICLE";

export const CREATE_ARTICLE = "CREATE_ARTICLE";
export const DELETE_ARTICLE = "DELETE_ARTICLE";
export const SAVE_ARTICLE = "SAVE_ARTICLE";
export const EDITOR_STATE_FILE_UPLOAD = "EDITOR_STATE_FILE_UPLOAD";
export const EDITOR_STATE_FILE_PREVIEW = "EDITOR_STATE_FILE_PREVIEW";
export const FILE_DELETE = "FILE_DELETE";

export const LOG_IN = "LOG_IN";
export const LOG_OUT = "LOG_OUT";
export const USER_STATUS_CHANGE = "USER_STATUS_CHANGE";

export const ICON_CAT_LOAD = "ICON_CAT_LOAD";
export const ICON_LOAD = "ICON_LOAD";
