export const UPDATE_APP_STATE = "UPDATE_APP_STATE";

export const APP_STATE = {
  EDIT:"EDIT",
  VIEW:"VIEW",
  INDEX:"INDEX",
  PUBLIC:"PUBLIC",
  INIT:"INIT"
}

export const UPDATE_EMAIL = "UPDATE_EMAIL";
export const UPDATE_QUESTION = "UPDATE_QUESTION";
export const RESET_QUESTION = "RESET_QUESTION";
export const SEND_QUESTION = "SEND_QUESTION"; //NOT DONE WAITING ON PROFILE

export const PULL_PROFILE = "PULL_PROFILE";
export const EDIT_PROFILE = "EDIT_PROFILE";
export const SAVE_PROFILE = "SAVE_PROFILE";

export const NETWORK_STATUS = {
  SUCCESS:"SUCCESS",
  ERROR:"ERROR",
  LOADING:"LOADING",
  INIT:"INIT"
}

export const QUESTION_STATUS = Object.assign({
  QUESTIONING:"QUESTIONING",
  EMAIL:"EMAIL",
  INVALIDEMAIL:"INVALIDEMAIL"
},NETWORK_STATUS)

export const PULL_ARTICLE_IDS = "PULL_ARTICLE_IDS";
export const PULL_GROUPS = "PULL_GROUPS";
export const PULL_DRAFT_IDS = "PULL_DRAFT_IDS";
